workflows:
  ios-release:
    name: Sambalam iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get
      - name: Install Pods
        script: |
          cd frontend/ios
          pod install
      - name: Flutter build IPA
        script: |
          cd frontend
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - akshayanatalla356@gmail.com # Your email from the screenshot