workflows:
  ios-release:
    name: Sambalam iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter pub get

      - name: Build IPA
        script: |
          cd frontend
          flutter build ipa --release --no-codesign

    artifacts:
      - frontend/build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - akshayanatalia356@gmail.com