const List<String> companyCategories = [
  'Agriculture/Farming',
  'Automobile Workshop',
  'Cable Service Provider',
  'Call Center',
  'Construction',
  'Contractor/Manpower Agency',
  'Distribution',
  'Educational Institute',
  'Financial Services',
  'Garments/Textiles',
  'Grocery/Kirana/General Store',
  'Gym/Health/Fitness',
  'Heavy Machinaery',
  'Hospital/Clinic',
  'Hotel/Lodge',
  'Internet Service Provider',
  'IT Software',
  'Jewellery',
  'Logistics/Transport',
  'Manufacturing',
  'News Channel',
  'NGO/Non-Profit',
  'Pest Control',
  'Pharmacy Store/Medical Store',
  'Printing',
  'Restaurant/Dhaba/Sweet Shop',
  'Saloon',
  'School',
  'Security Services',
  'Showroom/Outlet',
  'Supermarket',
  'Tailoring/Boutique',
  'Technology'
];
