// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqi0z_jlIIKyoF61526YVWh5lnbKTGPeI',
    appId: '1:995064371618:web:5e240660042d17e4b47afb',
    messagingSenderId: '995064371618',
    projectId: 'salarybox-95a05',
    authDomain: 'salarybox-95a05.firebaseapp.com',
    storageBucket: 'salarybox-95a05.firebasestorage.app',
    measurementId: 'G-7E96LC8FF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3gp1T3nJqAyO8JKNguUOSb9OUQYY8P0',
    appId: '1:995064371618:android:f07c1713dbfbf95bb47afb',
    messagingSenderId: '995064371618',
    projectId: 'salarybox-95a05',
    storageBucket: 'salarybox-95a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6pLWej1nJN7au-UpD94X0_iBFhTF3-g',
    appId: '1:995064371618:ios:d8768db86da82775b47afb',
    messagingSenderId: '995064371618',
    projectId: 'salarybox-95a05',
    storageBucket: 'salarybox-95a05.firebasestorage.app',
    iosBundleId: 'com.example.sambalam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq6pLWej1nJN7au-UpD94X0_iBFhTF3-g',
    appId: '1:995064371618:ios:d8768db86da82775b47afb',
    messagingSenderId: '995064371618',
    projectId: 'salarybox-95a05',
    storageBucket: 'salarybox-95a05.firebasestorage.app',
    iosBundleId: 'com.example.sambalam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqi0z_jlIIKyoF61526YVWh5lnbKTGPeI',
    appId: '1:995064371618:web:80008d3ebd6da3d4b47afb',
    messagingSenderId: '995064371618',
    projectId: 'salarybox-95a05',
    authDomain: 'salarybox-95a05.firebaseapp.com',
    storageBucket: 'salarybox-95a05.firebasestorage.app',
    measurementId: 'G-V12WD62553',
  );
}
